modified file extensions and paths of images and css links
sanscript-tech/orphan_support-php pull request #10
Opened 2020-10-18 14:22 UTC by sravani-7701

2020-10-18 14:31 UTC, ShauryaBhandari approved these changes
Approved.

2020-10-18 14:32 UTC, ShauryaBhandari requested changes
Please add some description about what you did when making a PR. Thanks!

2020-10-18 18:41 UTC, sravani-7701 commented
I have read all the code of the index file, nav file, etc folder and modified the path of img, css , js elements .

2020-10-19 04:28 UTC, Harshita248 approved these changes

2020-10-19 04:30 UTC, merged